### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by akuma527** [tobinjo96/CPFcluster#1]
Hi, 
Trying to fit the iris dataset to find the number of clusters. But get the following error:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-4821087451fc> in <module>
----> 1 result = CPFcluster.CPFclustering.train(X, k=2, K=3)

/opt/conda/lib/python3.7/site-packages/CPFcluster/core.py in train(cls, X, k, K, beta, reps, num_hashbits, blocksz, n_core)
     36       components = cls.get_components(X, k, edge_arr, w_arr)
     37       density, dists, bb, edge_arr, w_arr, ps = cls.get_density_dists_bb(X, K, components, reps, num_hashbits, blocksz, n_core)
---> 38       y = cls.get_y(edge_arr, w_arr, components, density, dists, bb, beta, k, K)
     39       result = cls(edge_arr, w_arr, components, density, dists, bb, y, ps)
     40       return result

/opt/conda/lib/python3.7/site-packages/CPFcluster/core.py in get_y(edge_arr, w_arr, components, density, dists, bb, beta, k, K)
    296     comps = np.unique((components[~np.isnan(components)])).astype(int)
    297     gamma = density * dists
--> 298     tosplit = [None]*(max(comps)+1)
    299     kmin = [None]*(max(comps)+1)
    300     nx = components.shape[0]

ValueError: max() arg is an empty sequence`

This the code I'm using:
`import CPFcluster`
`from sklearn.datasets import load_iris`
`df = load_iris()`
`X = df['data']`
`result = CPFcluster.CPFclustering.train(X, k=2, K=2)`

**Comment by tobinjo96** [comment]
Hi Anant, 

Thank you for your mail and for the interest shown in CPFcluster. 

I am currently working on an updated version of this method, and hope to release updated code in the next two weeks. I will ensure that the new version of the method does not suffer from the error you have included below. My advice would be to try the approach for larger values of k and K. I believe that currently, the method is not detecting any connected components above the minimum size. 

Thanks again,

Joshua 
……………...
Joshua Tobin

PhD Candidate
School of Computer Science & Statistics
Trinity College Dublin

Email: ***@***.*** ***@***.***>Web: https://statisticspg.scss.tcd.ie/ourgroup/joshua-tobin/ <https://statisticspg.scss.tcd.ie/ourgroup/joshua-tobin/>
